config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users
  root :to => "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:root_admin, :admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: { except: [:destroy] }, admin: :all, root_admin: :all

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSetup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<%= link_to "Home", root_path, class: 'navbar-brand' %>
		<ul class="nav navbar-nav ml-auto">
			<% if user_signed_in? %>
			  <div class="mr-5"><strong><%= link_to current_user.email, user_path(current_user) %></strong></div>
			  <li class="nav-item"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | </li> 
			  <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
			<% else %>
			  <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> | </li>
			  <li class="nav-item"><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
			<% end %>
		</ul>
	</nav>

	<% if notice %>
  	  <p class="alert alert-info"><%= notice %></p>
  	<% end %>
  	<% if alert %>
  	  <p class="alert alert-danger"><%= alert %></p>
  	<% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_user.html.slim
tr
	td = user.email
	td = link_to 'Show', user
	td = link_to 'Edit', edit_user_path(user)
	td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table.table
  thead
    tr
      th Email
      th
      th Action
      th

  tbody
    = render @users

br

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path